name: all_perks_streak_helper
description: All killer perks helper

publish_to: 'none'
version: 0.3.0

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11 
  file_picker: ^5.2.5
  flutter_colorpicker: ^1.0.3
  get: ^4.6.5
  shared_preferences: ^2.0.16
  http: ^0.13.5
  html: ^0.15.1
  reorderables: ^0.6.0
  context_menus: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/addons/
    - assets/images/addons/Artist/
    - assets/images/addons/Blight/
    - assets/images/addons/Cannibal/
    - assets/images/addons/Cenobite/
    - assets/images/addons/Clown/
    - assets/images/addons/Deathslinger/
    - assets/images/addons/Demogorgon/
    - assets/images/addons/Doctor/
    - assets/images/addons/Dredge/
    - assets/images/addons/Executioner/
    - assets/images/addons/Ghost_Face/
    - assets/images/addons/Hag/
    - assets/images/addons/Hillbilly/
    - assets/images/addons/Huntress/
    - assets/images/addons/Knight/
    - assets/images/addons/Legion/
    - assets/images/addons/Mastermind/
    - assets/images/addons/Nemesis/
    - assets/images/addons/Nightmare/
    - assets/images/addons/Nurse/
    - assets/images/addons/Oni/
    - assets/images/addons/OnryÅ/
    - assets/images/addons/Pig/
    - assets/images/addons/Plague/
    - assets/images/addons/Shape/
    - assets/images/addons/Skull_Merchant/
    - assets/images/addons/Spirit/
    - assets/images/addons/Trapper/
    - assets/images/addons/Trickster/
    - assets/images/addons/Twins/
    - assets/images/addons/Wraith/